//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SCREEN3
    {
        public int Id { get; set; }
        public int Screen1_ID { get; set; }
        public int Screen2_ID { get; set; }
        public string Status { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual SCREEN1 SCREEN1 { get; set; }
        public virtual SCREEN2 SCREEN2 { get; set; }
    }
}
