//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SCREEN1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCREEN1()
        {
            this.SCREEN2 = new HashSet<SCREEN2>();
            this.SCREEN3 = new HashSet<SCREEN3>();
        }
    
        public int ID { get; set; }
        public string EmployeeName { get; set; }
        public System.DateTime EntryDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime EmploymentDate { get; set; }
        public string Salary { get; set; }
        public bool IsTheEmployeeVaxx { get; set; }
        public int Age { get; set; }
        public string Position { get; set; }
        public string Admin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN2> SCREEN2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN3> SCREEN3 { get; set; }
    }
}
