//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employment.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SCREEN2
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SCREEN2()
        {
            this.SCREEN3 = new HashSet<SCREEN3>();
        }
    
        public int EmployeeID { get; set; }
        public string ProjectName { get; set; }
        public string ProjectManager { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ProjectStartDate { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime ProjectEndDate { get; set; }
        public string Department { get; set; }
        public string Admin { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual SCREEN1 SCREEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SCREEN3> SCREEN3 { get; set; }
    }
}
